name: mini-climate-data
channels:
  - conda-forge
dependencies:
  # Runtime
  - python>=3.10
  - pip
  - click
  - gitpython
  - jsonschema
  - pyyaml
  - tomli

  # Fetching
  - pooch

  # Reducers and source integrations
  - aiohttp
  - h5netcdf
  - intake
  - jinja2
  - nco
  - xarray

  # Tests and linting
  - pytest
  - ruff

  # Packaging
  - python-build
  - twine
